# Generated by Django 6.0.5 on 2026-05-19 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('poster', models.ImageField(upload_to='posters/')),
                ('actors', models.CharField(max_length=200, verbose_name='актеры')),
                ('release_date', models.DateField(verbose_name='дата релиза')),
                ('duration', models.PositiveIntegerField(verbose_name='длительность в минутах')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('language', models.CharField(max_length=100, verbose_name='язык')),
                ('budget', models.PositiveIntegerField(verbose_name='бюджет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('genres', models.ManyToManyField(to='CineBoard.genre', verbose_name='жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CineBoard.movie', verbose_name='фильм')),
            ],
        ),
        migrations.CreateModel(
            name='VIPBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата брони')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CineBoard.movie', verbose_name='фильм')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
